### ISSUE TITLE
using ng-multi-transclude within another ng-multi-transcluded directive.

### ISSUE THREAD

**Issue by jusopi** [zachsnow/ng-multi-transclude#14] opened 2014-11-19 17:26 UTC
plnkr - http://plnkr.co/edit/BZfv8NVwD9VraJC5GVoN?p=preview

I'm trying to build a series of 'components' using your ng-multi-transclude directive.  In a normal use case this is perfect.  But when trying to 'subclass' directives (the best way I can think of the usage paradigm), I get an error `Illegal use of ngMultiTransclude. No wrapping controller`

I have added the `ng-multi-transclude-controller` at the top level tag in the 'subclass' and I have also moved it down further into the template (which produces no error).  A normal `ng-transclude` tag works as expected (for instance in the case of the title controls in my example.

**Comment by joepb** [comment] 2015-02-19 14:59
Is there any idea for a workaround here? This is quite an annoying bug, since now I have to be aware of all functionality used inside templates for directives, all the way down the tree.

The issue seems to come from the rendering/transclusion of the outer template. When this happens, the parts that are evaluated (and try to start more multi-transclusions), aren't part of the tree at that time. They get added to the tree later. And therefore they cannot find their controllers...

**Comment by jusopi** [comment] 2015-02-19 15:40
@joepb I haven't visited this issue anymore since I just implemented what you alluded to (in this case I am only doing 2 levels of multi-transclude and am using unique names for the internal content).

But one thing that has come to mind after re-reading this whole issue is this:  Have you tried setting a higher priority on the outer wrapping directive?  I will try to test this here shortly.

**Comment by zachsnow** [comment] 2015-02-19 18:46
I believe that the issue is that controllers are not correctly available when transcluding (see #18 for another example); I'm looking at this and will try to release a fix soon. Apologies for the delay.

**Comment by zachsnow** [comment] 2015-03-07 17:26
This should be fixed in `master`.

**Closed by zachsnow** 2015-03-07 17:26 UTC
